# Generated by Django 5.1.15 on 2026-03-31 05:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('is_superuser', models.BooleanField(default=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('first_name', models.CharField(max_length=15)),
                ('last_name', models.CharField(max_length=15, null=True)),
                ('organisation_name', models.CharField(max_length=15, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('timezone', models.CharField(blank=True, max_length=50, null=True)),
                ('country', models.CharField(blank=True, max_length=50, null=True)),
                ('country_code', models.CharField(blank=True, max_length=4, null=True)),
                ('status', models.BooleanField(db_column='is_active', default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_application', models.BooleanField(default=False)),
                ('announcement_read_flag', models.IntegerField(default=1)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.PositiveIntegerField(blank=True, null=True)),
                ('modified_on', models.DateTimeField(null=True)),
                ('modified_by', models.PositiveIntegerField(blank=True, null=True)),
                ('auth0_id', models.CharField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'user',
                'ordering': ['first_name'],
            },
        ),
        migrations.CreateModel(
            name='TokenModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expiry_days', models.PositiveIntegerField()),
                ('expiry_time', models.DateTimeField(null=True)),
                ('type', models.CharField(choices=[('APP_TOKEN', 'APP_TOKEN'), ('LOGIN_TOKEN', 'LOGIN_TOKEN')], db_column='TOKEN_TYPE', default='APP_TOKEN', max_length=255)),
                ('primary_token', models.CharField(blank=True, max_length=120, null=True)),
                ('secondary_token', models.CharField(blank=True, max_length=120, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.PositiveIntegerField(null=True)),
                ('modified_on', models.DateTimeField(blank=True, null=True)),
                ('modified_by', models.PositiveIntegerField(null=True)),
                ('user_id', models.OneToOneField(db_column='user_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='token_user_id', to='user_management.user')),
            ],
            options={
                'db_table': 'TOKEN_MANAGEMENT',
                'ordering': ['-created_on'],
            },
        ),
    ]
