# Generated by Django 5.1.15 on 2026-03-31 05:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterPrivilege',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('privilege_name', models.CharField(db_column='PRIVILEGE_NAME', max_length=50, unique=True, verbose_name='Privilege')),
                ('privilege_desc', models.CharField(db_column='PRIVILEGE_DESC', max_length=1000, verbose_name='Privilege Description')),
                ('module_id', models.CharField(db_column='MODULE_ID', max_length=1000, verbose_name='Module Id')),
            ],
            options={
                'db_table': 'MASTER_PRIVILEGE',
                'ordering': ('privilege_name',),
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.PositiveIntegerField(null=True)),
                ('modified_on', models.DateTimeField(blank=True, null=True)),
                ('modified_by', models.PositiveIntegerField(null=True)),
                ('role_name', models.CharField(db_column='ROLE_NAME', max_length=50)),
                ('role_description', models.CharField(blank=True, db_column='ROLE_DESC', max_length=1000, null=True)),
            ],
            options={
                'db_table': 'ROLE',
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.PositiveIntegerField(null=True)),
                ('privilege', models.ForeignKey(db_column='PRIVILEGE_ID', on_delete=django.db.models.deletion.CASCADE, related_name='role_permission', to='acl.masterprivilege')),
                ('role', models.ForeignKey(db_column='ROLE_ID', on_delete=django.db.models.deletion.CASCADE, related_name='role_permission_role', to='acl.role')),
            ],
            options={
                'db_table': 'ROLE_PRIVILEGE',
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.PositiveIntegerField(null=True)),
                ('role', models.ForeignKey(db_column='ROLE_ID', on_delete=django.db.models.deletion.CASCADE, related_name='user_role_role', to='acl.role')),
                ('user', models.ForeignKey(db_column='USER_ID', on_delete=django.db.models.deletion.CASCADE, related_name='role_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'USER_ROLE',
                'ordering': ['-created_on'],
            },
        ),
    ]
