# Generated by Django 5.0.11 on 2025-11-09 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.PositiveIntegerField(null=True)),
                ('modified_on', models.DateTimeField(blank=True, null=True)),
                ('modified_by', models.PositiveIntegerField(null=True)),
                ('user_id', models.PositiveIntegerField(blank=True, db_index=True, null=True)),
                ('path', models.CharField(max_length=255)),
                ('method', models.CharField(max_length=10)),
                ('status_code', models.PositiveIntegerField()),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('request_body', models.JSONField(blank=True, null=True)),
                ('response_body', models.JSONField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Access Logs',
                'db_table': 'ACCESS_LOGS',
                'ordering': ['-created_on'],
                'indexes': [models.Index(fields=['user_id'], name='ACCESS_LOGS_user_id_8d20a4_idx'), models.Index(fields=['path'], name='ACCESS_LOGS_path_7566ed_idx'), models.Index(fields=['status_code'], name='ACCESS_LOGS_status__4f4b89_idx'), models.Index(fields=['created_on'], name='ACCESS_LOGS_created_8cba47_idx'), models.Index(fields=['user_id', 'created_on'], name='ACCESS_LOGS_user_id_7bde3e_idx')],
            },
        ),
        migrations.CreateModel(
            name='ErrorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.PositiveIntegerField(null=True)),
                ('modified_on', models.DateTimeField(blank=True, null=True)),
                ('modified_by', models.PositiveIntegerField(null=True)),
                ('user_id', models.PositiveIntegerField(blank=True, db_index=True, null=True)),
                ('path', models.CharField(max_length=255)),
                ('method', models.CharField(max_length=10)),
                ('status_code', models.PositiveIntegerField()),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('request_body', models.JSONField(blank=True, null=True)),
                ('response_body', models.JSONField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Error Logs',
                'db_table': 'ERROR_LOGS',
                'ordering': ['-created_on'],
                'indexes': [models.Index(fields=['user_id'], name='ERROR_LOGS_user_id_b320a9_idx'), models.Index(fields=['path'], name='ERROR_LOGS_path_df8876_idx'), models.Index(fields=['status_code'], name='ERROR_LOGS_status__6a8ccb_idx'), models.Index(fields=['created_on'], name='ERROR_LOGS_created_375aaf_idx'), models.Index(fields=['user_id', 'created_on'], name='ERROR_LOGS_user_id_a2dabc_idx')],
            },
        ),
    ]
