# Generated by Django 5.0.11 on 2025-11-09 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesslog',
            name='duration',
            field=models.FloatField(blank=True, help_text='Request duration in milliseconds', null=True),
        ),
        migrations.AddField(
            model_name='errorlog',
            name='duration',
            field=models.FloatField(blank=True, help_text='Request duration in milliseconds', null=True),
        ),
    ]
